[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = [
  'npm install --include=dev',
  '(cd backend && npm install --include=dev)',
  '(cd frontend && npm install --include=dev)'
]

[phases.build]
cmds = ['(cd frontend && npm run build)']

[start]
cmd = 'cd backend && npm start'
